apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: w268ek9px-nodejs-gitops
  description: This is GitOps manifest for w268ek9px-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=w268ek9px-nodejs
    backstage.io/kubernetes-id: w268ek9px-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: w268ek9px-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:w268ek9px-nodejs
