apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: w268ek9px-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-6b6352e682.243h.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:2005e0f74e866e0d313043939179d5840a811b11@sha256:c4cda6feb99cac4ef8fb0e6b62ae3661e9b9df0d01a77258e656bc72534efdf6
          name: container-image
